### ISSUE TITLE
Hello World ?

### ISSUE THREAD

**Issue by mal2994** [Lyatus/raccoon#4]
Raccoon looks completely awesome. Can you help me out with a hello world? I'm not getting anything from the virtual machine or the console. I can't tell if system is actually booting. The console is just stuck at "Rebooting...", I tried this on Edge and Firefox for windows. I didn't see any other program I could try to run. So, here is the program:
```
function init(){
  cls();
}
  
function draw(){
  print(0,0,"lol",8);  
}
function update(){
  debug("abc123");
}
```

I have it not paused, with autoapply on/off, I'm not getting anything.

**Comment by lut0pia** [comment]
Hello! Thanks for reaching out!

I just tested it and there was a bug with the log function, it should be fixed with https://github.com/Lyatus/raccoon/commit/8b393b1e8e88f30ce62ae819f94eaee0a830d5fb (just refreshing on your side should be enough to update). Also the color you chose for the `print` call is black (if you're using the default raccoon palette), so this could be why you cannot see the text on screen, try replacing the last parameter with 1 (white in default raccoon palette).

Tell me if that fixes everything or if you're still having trouble.

Have fun :)
